name: Docker

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: docker-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -f app/backend/Dockerfile .

      - name: Build frontend image
        run: docker build -f app/frontend/Dockerfile .

      - name: Build CMS image
        run: docker build ./app/cms
